coarse_tiles:
  type: coarse_tiles
  pitch: 0.1
  gap: 0.01
  power_per_tile: 1e-3
  noise: 50
  signal_fraction: 1
  threshold_sigma: 5.0

pixels:
  type: pixels
  pitch: 0.005
  power_per_pixel: 1.e-3
  noise: 50
  threshold_sigma: 4.0